version: '3'

services:
  postgres:
    image: 'postgres'
    restart: always
    env_file: ./.env
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-volume-test:/var/lib/postgresql/data
      # run sql start-up scripts to create and populate tables:
      #- ./db/createDbTables.sql:/docker-entrypoint-initdb.d/createDbTables.sql
      #- ./db/populateDbTables.sql:/docker-entrypoint-initdb.d/populateDbTables.sql
    ports:
      - '5432:5432'
    networks:
      - name-app

  ministrynameapp:
    image: ministrynameapp
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    env_file: ./.env
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    networks:
      - name-app

#volumes:
  #postgres-volume-test:
    #name: postgres-volume-test

networks:
  name-app: 
    driver: bridge

