version: '3.4'

services:
  ministrynameapp:
    image: ministrynameapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      #- 9229:9229
      - 5432:5432
    command: ["node", "--inspect=0.0.0.0:5432", "server.js"]
